### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by danmagnuz** [sm00v/Phonebook_CZ#1]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Phonebook_CZ/phonebook.py", line 75, in <module>
    emails = make_request(key)
             ^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/Phonebook_CZ/phonebook.py", line 29, in make_request
    key = json.loads(key)['id']
          ^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by sm00v** [comment]
> Traceback (most recent call last): File "/data/data/com.termux/files/home/Phonebook_CZ/phonebook.py", line 75, in emails = make_request(key) ^^^^^^^^^^^^^^^^^ File "/data/data/com.termux/files/home/Phonebook_CZ/phonebook.py", line 29, in make_request key = json.loads(key)['id'] ^^^^^^^^^^^^^^^ File "/data/data/com.termux/files/usr/lib/python3.11/json/**init**.py", line 346, in loads return _default_decoder.decode(s) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/data/data/com.termux/files/usr/lib/python3.11/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/data/data/com.termux/files/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Please go read my update in the readme. There is a new method to auth which you need to do before you can use this tool. LMK if you have anymore questions.

**Comment by nuoframework** [comment]
Hola, tengo el mismo error. Cuando inicio sesión en IntelligenceX, supongo que este es el token que debo poner:

![image](https://github.com/sm00v/Phonebook_CZ/assets/88777778/6fc78905-21c0-4b05-afbf-2e48c848dc6c)

Después lo pongo en el código:

![image](https://github.com/sm00v/Phonebook_CZ/assets/88777778/ad79b098-5ed5-49f1-8699-02f6331ca7c6)

Pero sigue sin funcionar:

![image](https://github.com/sm00v/Phonebook_CZ/assets/88777778/dde379f8-63b9-45a5-bb01-9e7bde5bef9e)
